
server:
  port: 8282

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/commande?currentSchema=commande&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: root1
    driver-class-name: org.postgresql.Driver
#  sql:
#    init:
#      platform: postgres
#      schema-locations: classpath:init-schema.sql,classpath:init-data.sql
#      mode: always
